### ISSUE TITLE
Default settings are not equal to Vanilla values

### ISSUE THREAD

**Issue by Veeyu22** [emipa606/DeepScannerSettings#2]
https://rimworldwiki.com/wiki/Ground-penetrating_scanner

![image](https://github.com/emipa606/DeepScannerSettings/assets/42015732/ebb177ee-3c95-4bc7-a842-f3727eabeb83)

A simple example of such is the default max node size of gold and jade are both set to 4, not 5.
Not a huge deal, but had to do some tweaking upon install.
Thanks for the helpful mod!!! Let me know if I am perhaps not understanding the values correctly? 
_(An example would be if the game automatically adds 1 to the node size, then adds a random value to reach the set range, so setting it to 4 makes the effective range 5, which I considered possible but wouldn't explain drilling cycles being different)_

**Comment by emipa606** [comment]
I dont think the wiki is updated as this is the actual definition in the xml:
![image](https://github.com/emipa606/DeepScannerSettings/assets/6932991/d1ca6afc-2918-4d82-bc4b-a5fe4a247380)
